# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Aravinth Panch
# Author: Aravinth Panch <ara@aracreate.group>
# Description: nRF54H20 DK: Kconfig fragment — app-specific config overrides

CONFIG_PRINTK=y
